added comments, added new functions for an error exit as well as a usage message, added tests for the positional parameters

diff --git a/trap_commands b/trap_commands
--- a/trap_commands
+++ b/trap_commands
@@ -3,25 +3,53 @@
 # Program to print a text file with headers and footers
 # (For now will just echo the contents of the file)
 
+# Usage: printfile file
+
+# Create temporary file name that gives preference to the user's local tmp 
+# directory and has a name that is resistant to "temp race attacks"
+
+if [ -d "~/tmp" ]; then
+	TEMP_DIR=~/tmp
+else
+	TEMP_DIR=/tmp
+fi
+
 TEMP_FILE=/tmp/printfile.txt
+PROGNAME=$(basename $0)
+
+usage() {
+	# Display usage message on standard error
+	echo "Usage: $PROGNAME file" 1>$2
+}
 
 clean_up() {
 	# Perform program exit housekeeping
-	rm $TEMP_FILE
-	exit
+	# Optionally accepts an exit status
+	rm -f $TEMP_FILE
+	exit $1
 }
 
-# The trap command listens for the three signals specified and then runs the   
-# commands in quotes
+error_exit() {
+	# Display error message and exit
+	echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+	clean_up 1
+}
 
 trap clean_up SIGHUP SIGINT SIGTERM
 
-pr $1 > $TEMP_FILE
+if [ $# != "1" ]; then
+	usage
+	error_exit "one file to print must be specified"
+fi
+if [ ! -f "$1" ]; then
+	error_exit "file $1 cannot be read"
+fi
+
+pr $1 > $TEMP_FILE || error_exit "cannot format file"
 
 echo -n "Print file? [y/n]: "
 read
 if [ "$REPLY" = "y" ]; then
-	cat $TEMP_FILE
+	cat $TEMP_FILE || error_exit "cannot read file"
 fi
-
 clean_up
